### ISSUE TITLE
link is never generated

### ISSUE THREAD

**Issue by eyetest42** [arenasys/arenasys.github.io#1]
gets stuck at "SERVER: starting"

**Comment by arenasys** [comment]
https://www.cloudflarestatus.com/
Cloudflare is having troubles. You can try the Kaggle notebook if you want.

**Comment by eyetest42** [comment]
Kaggle gives me a "Torch not compiled with CUDA enabled" error when I try to generate

**Comment by arenasys** [comment]
Need to enable GPU's for kaggle, which needs a verified account (need to give them your phone num iirc). 
![image](https://github.com/arenasys/arenasys.github.io/assets/79061310/f0636f51-4b16-4719-b76a-9f50c29040dd)
I wont get into it here though.
