### ISSUE TITLE
Never connects

### ISSUE THREAD

**Issue by eyetest42** [arenasys/arenasys.github.io#2]
after opening the Cloudflare link, the UI says "disconnected" and nothing happens when I click on anything. it's almost as if the password provided is wrong.
Cloudflare is working at the time of this writing.

**Comment by arenasys** [comment]
Seems to be fixed by https://github.com/arenasys/qDiffusion/commit/550983aec20bd7c21e6e34eb3534a3d7520fa5fb. Remake the colab notebook.

**Comment by eyetest42** [comment]
thanks, that did the trick
